version: "3.5"

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    volumes:
      - /tmp/walkingshadows/data/mongodb:/data/db
      - /tmp/walkingshadows/data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  redis-stack:
    image: redis/redis-stack:7.0.6-RC7
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /tmp/walkingshadows/data/redis:/data

  ws-world:
    image: ws-world:latest
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGODB_URL: mongodb://root:example@mongo:27017/
      LOGURU_LEVEL: INFO
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis-stack
