version: "3.5"

networks:
  backend:
    name: backend
    driver: bridge

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    networks:
      - backend
    volumes:
      - ./data/mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  ws-world:
    image: ws-world:latest
    restart: always
    networks:
      - backend
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongo
