version: "3.5"

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    volumes:
      - /tmp/walkingshadows/data/mongodb:/data/db
      - /tmp/walkingshadows/data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  ws-world:
    image: ws-world:latest
    restart: always
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
      LOGURU_LEVEL: INFO
    ports:
      - "8000:8000"
    depends_on:
      - mongo
