name: Warm up cache - daily run

on:
  schedule:
    - cron: "0 16 * * *" # Every day at 12 AM GMT+8 (UTC 4 PM)

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env file
        id: create-dot-env
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        shell: bash

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Bazel Cache
        id: bazel-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-bazel-cache-

      - uses: bazelbuild/setup-bazelisk@v1

      - name: Run All Tests
        run: |
          ./scripts/test.sh
